//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGioiSanKhau {
    
    
    public partial class _default {
        
        /// <summary>
        /// SlideShow1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.SlideShow SlideShow1;
        
        /// <summary>
        /// ListNewsLink1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.ListNewsLink ListNewsLink1;
        
        /// <summary>
        /// ListNewsLink2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.ListNewsLink ListNewsLink2;
        
        /// <summary>
        /// QuangCaoNgang1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.QuangCaoNgang QuangCaoNgang1;
        
        /// <summary>
        /// ListNewsTopImage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.ListNewsTopImage ListNewsTopImage1;
        
        /// <summary>
        /// ListNewsTopImage2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.ListNewsTopImage ListNewsTopImage2;
        
        /// <summary>
        /// ListNewsTopImage3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.ListNewsTopImage ListNewsTopImage3;
        
        /// <summary>
        /// ListNewsTopImage4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.ListNewsTopImage ListNewsTopImage4;
        
        /// <summary>
        /// QuangCao4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.QuangCao QuangCao4;
        
        /// <summary>
        /// HotVideo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.HotVideo HotVideo1;
        
        /// <summary>
        /// HotPhoto1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.HotPhoto HotPhoto1;
        
        /// <summary>
        /// QuangCaoLon1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TheGioiSanKhau.ctrl.QuangCaoLon QuangCaoLon1;
    }
}
